### ISSUE TITLE
Cannot start any Virtualbox session while flatkvm session is open

### ISSUE THREAD

**Issue by github467080** [flatkvm/flatkvm#1]
Failed to open a session for the virtual machine openSUSE.

VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).

VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: ConsoleWrap
Interface: IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by slp** [comment]
Thanks for reporting this issue.

Flatkvm uses KVM, which implies loading and initializing **kvm.ko**. As there can't be multiple virtualization technologies simultaneously enabled on the same machine, VirtualBox can't operate when there's a Flatkvm app running.

As there is no possible solution, I've added this information to the **Known Issues** section in README.md, and I'm closing this issue.
