### ISSUE TITLE
Allow non-english keyboards

### ISSUE THREAD

**Issue by SISheogorath** [flatkvm/flatkvm#4]
While trying to run Riot in FlatKVM I noticed that the input is limited to an US keyboard. I couldn't really find a way to change it, so I guess that it's not possible yet and (maybe) hardcoded in the VM image.

No pressure, we have all time in the world, just wanted to give a heads up :wink:

**Comment by slp** [comment]
You're right. My intention was capturing the keyboard layout from the Host, and instructing the Agent to set it up on the VM, but, well... I forgot about it ;-)

This is the next thing I'm going to implement, quite possibly this very week.

Thanks for reporting it!

**Comment by slp** [comment]
Fixed by d0b8343c324bc264f9df9c0bf5da51019440f32d and included in 0.1.6 release.
